# Jim; Copied this off stack overflow. Not sure about this, does seem to ignore my failing unite tests... Give up!
# Also, I can't get it to run automatically - it can only be triggered from the UI. Shouldn't it run on every commit
# or something?
name: CI pipeline
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn --no-transfer-progress -B compile --file pom.xml
        
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
